### ISSUE TITLE
Implement Graph Display Feature 🎯

### ISSUE THREAD

**Issue by boroboro01** [boroboro01/RedThread#1]
# Description
Drawing network graph

# Tasks

### Graph
- [ ] Display the graph on the screen

### Group
- [ ] Implement the feature to add groups
- [ ] Implement the feature to edit groups
- [ ] Implement the feature to delete groups

### Relationship
- [ ] Implement the feature to add relationships
- [ ] Implement the feature to edit relationships
- [ ] Implement the feature to delete relationships

### Elastic
- [ ] Dynamically adjust the size of circles

# Additional Context
<img width="288" alt="image" src="https://github.com/user-attachments/assets/e734dc7a-97f3-4ec4-9a7f-284fabdd0ef6">
